import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import FollowBar from "@/components/FollowBar";
import LoginModal from "@/components/modals/LoginModal";
import SignupModal from "@/components/modals/SignupModal";
import { Toaster } from "react-hot-toast";
import Provider from "./provider";
import TweetModal from "@/components/modals/TweetModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TweetKar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <Toaster />
          <div className="h-screen">
            <div className="container h-full mx-auto xl:px-30 max-w-6xl">
              <div className="grid grid-cols-4 h-full">
                <Sidebar />
                <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-200">
                  {children}
                </div>
                <FollowBar />
              </div>
            </div>
            <LoginModal />
            <SignupModal />
            <TweetModal />
          </div>
        </body>
      </Provider>
    </html>
  );
}
